### PR TITLE
Feature/security

### PR DESCRIPTION
**Pull request by Shemarama**
This also includes my other pull request.  I added some basic encryption/decryption in the UDPConnection class.

### CODE REVIEW

**Review by katiesweet — COMMENTED** [review]
@Shemarama I'm a little confused on how this is working. To me, it looks like the Registry's private key is known to everyone? I'm a little concerned that defeats the "security" portion of having public and private keys. Is that how this works, or am I reading the code wrong?

**Comment by Shemarama** [comment]
If we were to deploy this, only the Registry would actually have the private key file (right now the project has all of the Process files packed into one).  The Registry's private key in the tests is just for me to make sure it is working.  I'm going to remove the one in the test folder after I get it completely working.

If another process tried to read the Private key file, it wouldn't find it since it wouldn't have any of the Registry's files (It would only have its own Process files, Comm Layer, and shared messages).

**Comment by katiesweet** [comment]
@Shemarama Okay great, thank you!

**Comment by katiesweet** [comment]
Works great @Shemarama

**Pull request merged**
