### PR TITLE
Feature/communication subsystem

### PR DESCRIPTION
**Pull request by katiesweet**
Added logging and unit tests for communication subsystem. I had a hard time knowing how to write unit tests for the subsystem since a lot of it is interdependent... If you guys have suggestions, let me know.

Also, I gave Registry.py a temporary fixed endpoint (localhost, 50000) so we don't have to type it in every time.

### CODE REVIEW

**Review by Shemarama — COMMENTED** [review]
When trying to run the tests I'm getting this error:


....Unhandled exception in thread started by <bound method UdpConnection.__run of <CommunicationLibrary.CommunicationSubsystem.UdpConnection.UdpConnection instance at 0x7f9bec13f170>>Unhandled exception in thread started by <bound method UdpConnection.__run of <CommunicationLibrary.CommunicationSubsystem.UdpConnection.UdpConnection instance at 0x7f9bec1381b8>>.

Traceback (most recent call last):
Traceback (most recent call last):
  File "../../CommunicationLibrary/CommunicationSubsystem/UdpConnection.py", line 50, in __run
    udpSocket.bind(myEndpoint)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 98] Address already in use  File "../../CommunicationLibrary/CommunicationSubsystem/UdpConnection.py", line 50, in __run
    
.
udpSocket.bind(myEndpoint)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: ----------------------------------------------------------------------Unhandled exception in thread started by <bound method UdpConnection.__run of <CommunicationLibrary.CommunicationSubsystem.UdpConnection.UdpConnection instance at 0x7f9bec13fbd8>>
[Errno 98] Address already in use
Ran 6 tests in 0.002s
Traceback (most recent call last):
  File "../../CommunicationLibrary/CommunicationSubsystem/UdpConnection.py", line 50, in __run
    
udpSocket.bind(myEndpoint)

  File "/usr/lib/python2.7/socket.py", line 228, in meth
OK

**Comment by katiesweet** [comment]
@Shemarama The error shows an "address already in use". In the test script, I arbitrarily am using "localhost" port 50000. I'm thinking that port may be in use on your computer? Do you have the registry running at the same time? I used the same arbitrary port of 50000 there. What I should have done is put port 0 since that will bind to an operating system assigned open port. Try changing the tests to have endpoint ("localhost", 0) and see if that fixes it.

**Comment by Shemarama** [comment]
I didn't have the Registry running.

Okay, after changing the port to 0 I'm getting another message:

......
----------------------------------------------------------------------Unhandled exception in thread started by <bound method UdpConnection.__run of <CommunicationLibrary.CommunicationSubsystem.UdpConnection.UdpConnection instance at 0x7ff071da6368>>

Traceback (most recent call last):
  File "../../CommunicationLibrary/CommunicationSubsystem/UdpConnection.py", line 60, in __run
Ran 6 tests in 0.002s    
self.__sendMessage(udpSocket, self.outgoingMessageQueue.get())

  File "../../CommunicationLibrary/CommunicationSubsystem/UdpConnection.py", line 24, in __sendMessage
OK

**Comment by Shemarama** [comment]
It seems like the tests run fine.  I was reading something on stackoverflow about the client throwing an exception when disconnecting, but wrapping every function with try except blocks didn't help.

**Comment by katiesweet** [comment]
@Shemarama will you please see if this fixed the unit test bug for you?

**Comment by Shemarama** [comment]
That fixed it!  I will merge this

**Pull request merged**
